name: C++ CI Workflow

on:
  push:
  pull_request:

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies (g++)
      run: sudo apt update && sudo apt install -y g++

    - name: Compile Code
      run: g++ -o bank bank.cpp

    - name: Run Program
      run: echo "Run the program !!!" && ./bank < input.txt || true
      
